server:
  port: 3344

#可以通过http：//localhost:8899/
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/827164881/bootcloud-config.git
  #      可以指定label，默认就是master
  #      label: master
  # 增加对rabbitmq的支持
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true

# rabbitmq配置，暴露bus刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
